### ISSUE TITLE
"About" Information on Front Page?

### ISSUE THREAD

**Issue by jackpolifka** [markkanthonyf/markkanthonyf.github.io#1]
What is your opinion about putting the content on the "About" page on index.html? When someone visits your site, I think it would be good for them to see a photo of you and your quick bio. That helps to inform viewers who are you and what you do right away. It also confirms that they are visiting the current site.

**Comment by markkanthonyf** [comment]
I can definiley try that out! My initial instinct is to put my best work as the first thing so people see what I can do. Though you bring up a great point and I will switch those around.
