### ISSUE TITLE
One Page Layout for Portfolio Website?

### ISSUE THREAD

**Issue by jackpolifka** [markkanthonyf/markkanthonyf.github.io#2]
I am confused about the page layout of your website at the moment. What is the difference between the main page and the "Projects" page? What is your opinion about combining them together? That would create a larger, more complete timeline on one page. People wouldn't need to click another hyperlink to get more information about your skills. Currently, I do not know if you need a separate page for "Projects'. What are your thoughts?

**Comment by markkanthonyf** [comment]
I had done it so the "home page" tells the story of my work as I've gotten better, and the projects page is for work that I've done as a grade, a job, commission, or what have you. I do see the confusion, though you're right. I'll try converting it to one page.
